- name: Virtual network
      debug:

    
    - name: Create virtual network
      azure_rm_virtualnetwork:
        ...

    - name: Subnet
      debug:
        msg: "Go to subnet doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_subnet_module.html"
  
  
    - name: Public IP address
      debug:
        msg: "Go to public ip address https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_publicipaddress_module.html"

    - name: Create public IP address
      azure_rm_publicipaddress:
        name: "{{public_ip_name}}"
        
    # Vous pouvez laisser cette partie en bas inchangée, pourvu que les noms de 
    # variables pour les tasks suivantes "Network Security Group", "Network Interface" 
    # et "Create your Windows VM".

    # - name: Output public IP
    #   debug:
    #     msg: "The public IP is {{ output_ip_address.state.ip_address }}"

    # - name: Network Security Group
    #   debug:
    #     msg: "Go to Network Security Group doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_securitygroup_module.html"

    

    # - name: Network Interface
    #   debug:
    #     msg: "Go to network interface doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_networkinterface_module.html"

    
    # - name: Create your VM
    #   debug:
    #     msg: "Go to vm doc https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create"

    # - name: Create your windows VM
    #   shell: |
    #     az vm create \
    #       --resource-group ansible-rg \
    #       --name testvm12 \
    #       --image Win2022AzureEditionCore \
    #       --public-ip-sku Standard \
    #       --admin-username "{{lookup('env', 'vm_user')}}" \
    #       --admin-password "{{lookup('env', 'vm_password')}}" \
    #       --vnet-name "{{vnet_name}}"