---
- hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: /usr/bin/python3
    vnet_name: vnet-bridge
    vnet_subnet: subnet0
    public_ip_name: myDomain
    security_group_name: networkSecurityGroup


  tasks:
    - name: Login to azure
      shell: az login --username "{{lookup('env', 'email')}}" --password "{{lookup('env', 'password')}}"
      register: ps

    - name: Create a resource group
      azure_rm_resourcegroup:
        name: IAAS_GRP
        location: eastus

    - name: Create Virtual network
      azure_rm_virtualnetwork:
        resource_group: IAAS_GRP
        name: IAAS_LAN
        address_prefixes_cidr: 10.11.12.0/24
        msg: "Go to virtual network doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_virtualnetwork_module.html"

    - name: Create a subnet
      azure_rm_subnet:
        resource_group: IAAS_GRP
        virtual network name: IAAS_GRP_Network
        name: IAAS_GRP_Subnet
        address_prefixes_cidr: "10.11.12.0/24"
  
      # debug:
      #   msg: "Go to ressource group doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_resourcegroup_module.html"