---
- hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: /usr/bin/python3
    vnet_name: vnet-bridge
    vnet_subnet: subnet0
    public_ip_name: myDomain
    security_group_name: networkSecurityGroup


  tasks:
    - name: Login to azure
      shell: az login --username "{{lookup('env', 'email')}}" --password "{{lookup('env', 'password')}}"
      register: ps

    - name: Create a resource group
      azure_rm_resourcegroup:
        name: IAAS_GRP
        location: eastus

    - name: Create Virtual network
      azure_rm_virtualnetwork:
        resource_group: IAAS_GRP
        name: IAAS_GRP_Network
        address_prefixes_cidr: 10.11.12.0/24
        # msg: "Go to virtual network doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_virtualnetwork_module.html"

    - name: Create a Subnet
      azure_rm_subnet:
        resource_group: IAAS_GRP
        virtual_network_name: IAAS_GRP_Network
        name: IAAS_GRP_Subnet
        address_prefix_cidr: "10.11.12.0/24"

    - name: Create a public ip address
      azure_rm_publicipaddress:
        resource_group: IAAS_GRP
        name: IAAS_GRP_PublicAddress
        allocation_method: static
        domain_name: iaasdomain
      register: output_ip_domain
    
    - name: Output public IP
      debug:

    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: IAAS_GRP
        name: IAAS_Security_Group

        rules:
          - name: 'allow_rdp'
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1001
            direction: Inbound
          - name: 'allow_web_traffic'
            protocol: Tcp
            destination_port_range:
              - 80
              - 443
            access: Allow
            priority: 1002
            direction: Inbound
          - name: 'allow_powershell_remoting'
            protocol: Tcp
            destination_port_range: 
              - 5985
              - 5986
            access: Allow
            priority: 1003
            direction: Inbound

    - name: Delete network interface
      azure_rm_networkinterface:
        resource_group: IAAS_GRP
        name: IAAS_GRP-vNet
        state: absent

    - name: Create a network interface
      azure_rm_networkinterface:
        name: iaas_interface
        resource_group: IAAS_GRP
        virtual_network: IAAS_GRP_Network
        subnet_name: IAAS_GRP_Subnet
        security_group: IAAS_Security_Group
        public_ip_address_name: "IAAS_GRP_PublicAddress"
        state: present
    
    - name: Create VM
      azure_rm_virtualmachine:
        name: iaas_interface
        resource_group: IAAS_GRP
        image: Win2022AzureEditionCore
        public-ip-sku: Standard 
        admin-username: "{{lookup('env', 'vm_user')}}"
        admin-password: "{{lookup('env', 'vm_password')}}"
        vnet-name: "{{vnet_name}}"


        # msg: "The public IP is {{ output_ip_address.state.ip_address }}"
  
      # debug:
      #   msg: "Go to ressource group doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_resourcegroup_module.html"